# Generated by Django 4.2.4 on 2023-11-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('result', '0001_initial'),
        ('questions', '0003_questiongroup_q_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_true', models.BooleanField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_prof_answers', related_query_name='question_prof_answer', to='questions.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_prof_answers', related_query_name='result_prof_answer', to='result.result')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
