# Generated by Django 4.2.4 on 2023-12-05 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taker', '0005_remove_profileanswer_match_profileanswer_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileanswer',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', related_query_name='student_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
