# Generated by Django 4.2.4 on 2024-03-03 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_examquestion_exam_questions'),
        ('taker', '0006_profileanswer_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileanswer',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_answer', to='exams.exam'),
        ),
    ]
