# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-23 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import questions.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=questions.utils.image_path)),
                ('audio', models.FileField(blank=True, upload_to=questions.utils.audio_path)),
                ('barm', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
