# Generated by Django 4.2.4 on 2023-10-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='q_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_bank_q_groups', related_query_name='q_bank_q_group', to='questions.questionbank'),
        ),
    ]
