# Generated by Django 4.2.4 on 2023-11-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questiongroup_q_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_true',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
