# Generated by Django 4.2.4 on 2023-08-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='queston_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_group_questions', related_query_name='question_group_question', to='questions.questiongroup'),
        ),
    ]
