# Generated by Django 4.2.4 on 2023-11-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='item_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
