# Generated by Django 4.2.4 on 2023-10-26 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.IntegerField(max_length=200)),
                ('group_code', models.IntegerField(max_length=200)),
                ('term', models.IntegerField(max_length=200)),
                ('year', models.DateField(default=datetime.date(2023, 1, 1))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
