# Generated by Django 4.2.4 on 2023-10-30 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questiongroup_q_bank'),
        ('course', '0002_course_question_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_bank_courses', to='questions.questionbank'),
        ),
    ]
