# Generated by Django 4.2.4 on 2023-11-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_students_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group_code',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
