# Generated by Django 4.2.4 on 2023-09-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField(blank=True)),
                ('duration', models.TimeField(blank=True)),
            ],
        ),
    ]
