# Generated by Django 4.2.4 on 2023-09-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='duration',
            new_name='start',
        ),
    ]
