# Generated by Django 4.2.4 on 2023-09-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_duration_exam_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='deadline',
            field=models.DateField(blank=True),
        ),
    ]
