# Generated by Django 4.2.4 on 2023-09-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_questiongroup_exam'),
        ('exams', '0003_alter_exam_deadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
