# Generated by Django 4.2.4 on 2023-09-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_rename_end_exam_duration_remove_exam_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DurationField(blank=True),
        ),
    ]
