# Generated by Django 4.2.4 on 2023-09-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_exam_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DurationField(default=None),
        ),
        migrations.AlterField(
            model_name='exam',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
