# Generated by Django 4.2.4 on 2023-09-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0004_delete_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('deadline', models.DateField(blank=True)),
                ('start', models.TimeField(blank=True)),
                ('end', models.TimeField(blank=True)),
            ],
        ),
    ]
