# Generated by Django 4.2.4 on 2023-09-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_exam_created_at_alter_exam_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='action',
            field=models.BooleanField(default=False),
        ),
    ]
