# Generated by Django 4.2.4 on 2023-10-04 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='percent_passing_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='exam',
            name='point_passing_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='exam',
            name='score_type',
            field=models.CharField(choices=[('PE', 'PERCENT'), ('PO', 'POINT')], default='PO', max_length=2),
        ),
    ]
