# Generated by Django 4.2.4 on 2023-10-04 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_percent_passing_score_exam_point_passing_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='incorrect_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='unanswered_penalty',
            field=models.BooleanField(default=False),
        ),
    ]
