# Generated by Django 4.2.4 on 2023-10-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_incorrect_penalty_exam_shuffle_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
