# Generated by Django 4.2.4 on 2023-10-31 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_question_bank'),
        ('exams', '0009_alter_exam_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_exams', to='course.course'),
        ),
    ]
