# Generated by Django 4.2.4 on 2023-12-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_exam_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='question_type',
            new_name='exam_status',
        ),
    ]
