# Generated by Django 4.2.4 on 2024-01-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_exam_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='manual_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
