# Generated by Django 4.2.4 on 2024-01-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_exam_manual_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='avg_score',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
