# Generated by Django 4.2.4 on 2024-03-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_exam_avg_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
    ]
