# Generated by Django 4.2.4 on 2024-04-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_examquestion_exam_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.CharField(default='1403-02-01 18:04:27', max_length=20, verbose_name='Persian Datetime'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
