# Generated by Django 4.2.4 on 2024-04-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_exam_exam_date_exam_exam_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.CharField(default='1403-02-01', max_length=20, verbose_name='Persian Datetime'),
        ),
    ]
