# Generated by Django 4.2.4 on 2024-05-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_alter_exam_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.CharField(default='1403/02/24', max_length=20, verbose_name='Persian Datetime'),
        ),
    ]
