# Generated by Django 4.2.4 on 2024-08-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0026_alter_exam_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.CharField(default='1403/05/18', max_length=20, verbose_name='Persian Datetime'),
        ),
    ]
