# Generated by Django 4.2.4 on 2023-12-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_entry_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='major_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
