# Generated by Django 4.2.4 on 2023-10-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_accesslevel_remove_profile_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_level',
            field=models.CharField(blank=True, choices=[('S', 'Student'), ('A', 'Admin')], max_length=10, null=True),
        ),
    ]
