# Generated by Django 4.2.4 on 2023-12-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_major_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='entry_year',
            field=models.CharField(blank=True, null=True),
        ),
    ]
