# Generated by Django 4.2.4 on 2024-01-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_entry_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_level',
            field=models.CharField(blank=True, choices=[('S', 'Student'), ('A', 'Admin')], max_length=1, null=True),
        ),
    ]
